# Name for the demo
name: CICD

# actions and branch name 
# on which perform task
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12' ]
    name: Node ${{ matrix.node }} sample
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
#       - run: npm install
      

      - name: Build the hello-world Docker image
        run: |
           echo $CR_PAT | docker login ghcr.io -u ommore1523 --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}

      - name: Build & push docker image 
        run: |
           pushDatetime=$(date '+%B-%d_%H-%M-%S')
           docker build . -t ghcr.io/ommore1523/nodeapp:$pushDatetime
           docker push ghcr.io/ommore1523/nodeapp:$pushDatetime

